
import type { Belt } from './types';

export const COUNTRIES = [
  { code: "US", name: "United States" },
  { code: "GB", name: "United Kingdom" },
  { code: "CA", name: "Canada" },
  { code: "AU", name: "Australia" },
  { code: "DE", name: "Germany" },
  { code: "FR", name: "France" },
  { code: "ES", name: "Spain" },
  { code: "IT", name: "Italy" },
  { code: "NL", name: "Netherlands" },
  { code: "BE", name: "Belgium" },
  { code: "AT", name: "Austria" },
  { code: "CH", name: "Switzerland" },
  { code: "SE", name: "Sweden" },
  { code: "NO", name: "Norway" },
  { code: "DK", name: "Denmark" },
  { code: "FI", name: "Finland" },
  { code: "IE", name: "Ireland" },
  { code: "PT", name: "Portugal" },
  { code: "PL", name: "Poland" },
  { code: "CZ", name: "Czech Republic" },
  { code: "HU", name: "Hungary" },
  { code: "RO", name: "Romania" },
  { code: "BG", name: "Bulgaria" },
  { code: "HR", name: "Croatia" },
  { code: "SK", name: "Slovakia" },
  { code: "SI", name: "Slovenia" },
  { code: "GR", name: "Greece" },
  { code: "CY", name: "Cyprus" },
  { code: "MT", name: "Malta" },
  { code: "LU", name: "Luxembourg" },
  { code: "EE", name: "Estonia" },
  { code: "LV", name: "Latvia" },
  { code: "LT", name: "Lithuania" },
  { code: "JP", name: "Japan" },
  { code: "KR", name: "South Korea" },
  { code: "CN", name: "China" },
  { code: "TW", name: "Taiwan" },
  { code: "HK", name: "Hong Kong" },
  { code: "SG", name: "Singapore" },
  { code: "MY", name: "Malaysia" },
  { code: "TH", name: "Thailand" },
  { code: "VN", name: "Vietnam" },
  { code: "PH", name: "Philippines" },
  { code: "ID", name: "Indonesia" },
  { code: "IN", name: "India" },
  { code: "PK", name: "Pakistan" },
  { code: "BD", name: "Bangladesh" },
  { code: "NP", name: "Nepal" },
  { code: "LK", name: "Sri Lanka" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "QA", name: "Qatar" },
  { code: "KW", name: "Kuwait" },
  { code: "BH", name: "Bahrain" },
  { code: "OM", name: "Oman" },
  { code: "IL", name: "Israel" },
  { code: "TR", name: "Turkey" },
  { code: "EG", name: "Egypt" },
  { code: "ZA", name: "South Africa" },
  { code: "NG", name: "Nigeria" },
  { code: "KE", name: "Kenya" },
  { code: "GH", name: "Ghana" },
  { code: "MX", name: "Mexico" },
  { code: "BR", name: "Brazil" },
  { code: "AR", name: "Argentina" },
  { code: "CO", name: "Colombia" },
  { code: "CL", name: "Chile" },
  { code: "PE", name: "Peru" },
  { code: "VE", name: "Venezuela" },
  { code: "EC", name: "Ecuador" },
  { code: "UY", name: "Uruguay" },
  { code: "PY", name: "Paraguay" },
  { code: "BO", name: "Bolivia" },
  { code: "CR", name: "Costa Rica" },
  { code: "PA", name: "Panama" },
  { code: "DO", name: "Dominican Republic" },
  { code: "JM", name: "Jamaica" },
  { code: "TT", name: "Trinidad and Tobago" },
  { code: "NZ", name: "New Zealand" },
  { code: "RU", name: "Russia" },
  { code: "UA", name: "Ukraine" },
  { code: "BY", name: "Belarus" },
  { code: "KZ", name: "Kazakhstan" },
  { code: "UZ", name: "Uzbekistan" },
  { code: "AF", name: "Afghanistan" },
  { code: "IQ", name: "Iraq" },
  { code: "IR", name: "Iran" },
  { code: "JO", name: "Jordan" },
  { code: "LB", name: "Lebanon" },
  { code: "SY", name: "Syria" },
  { code: "YE", name: "Yemen" },
  { code: "PS", name: "Palestine" },
  { code: "MA", name: "Morocco" },
  { code: "DZ", name: "Algeria" },
  { code: "TN", name: "Tunisia" },
  { code: "LY", name: "Libya" },
  { code: "SD", name: "Sudan" },
  { code: "ET", name: "Ethiopia" },
  { code: "TZ", name: "Tanzania" },
  { code: "UG", name: "Uganda" },
  { code: "RW", name: "Rwanda" },
  { code: "SN", name: "Senegal" },
  { code: "CI", name: "Ivory Coast" },
  { code: "CM", name: "Cameroon" },
  { code: "AO", name: "Angola" },
  { code: "MZ", name: "Mozambique" },
  { code: "ZW", name: "Zimbabwe" },
  { code: "ZM", name: "Zambia" },
  { code: "BW", name: "Botswana" },
  { code: "NA", name: "Namibia" },
  { code: "MU", name: "Mauritius" },
  { code: "IS", name: "Iceland" },
  { code: "RS", name: "Serbia" },
  { code: "BA", name: "Bosnia and Herzegovina" },
  { code: "ME", name: "Montenegro" },
  { code: "MK", name: "North Macedonia" },
  { code: "AL", name: "Albania" },
  { code: "MD", name: "Moldova" },
  { code: "GE", name: "Georgia" },
  { code: "AM", name: "Armenia" },
  { code: "AZ", name: "Azerbaijan" },
  { code: "MN", name: "Mongolia" },
  { code: "KH", name: "Cambodia" },
  { code: "LA", name: "Laos" },
  { code: "MM", name: "Myanmar" },
  { code: "BN", name: "Brunei" },
  { code: "FJ", name: "Fiji" },
  { code: "PG", name: "Papua New Guinea" },
  { code: "NC", name: "New Caledonia" },
  { code: "MV", name: "Maldives" },
  { code: "BT", name: "Bhutan" },
  { code: "MC", name: "Monaco" },
  { code: "AD", name: "Andorra" },
  { code: "LI", name: "Liechtenstein" },
  { code: "SM", name: "San Marino" },
  { code: "VA", name: "Vatican City" },
  { code: "CU", name: "Cuba" },
  { code: "HT", name: "Haiti" },
  { code: "BS", name: "Bahamas" },
  { code: "BB", name: "Barbados" },
  { code: "BZ", name: "Belize" },
  { code: "GT", name: "Guatemala" },
  { code: "HN", name: "Honduras" },
  { code: "NI", name: "Nicaragua" },
  { code: "SV", name: "El Salvador" },
  { code: "GY", name: "Guyana" },
  { code: "SR", name: "Suriname" },
  { code: "PR", name: "Puerto Rico" },
];

export const LANGUAGES = [
    "English", "French", "German"
];

// Heuristic map to suggest language based on country
export const COUNTRY_LANGUAGE_MAP: Record<string, string> = {
    "United States": "English", "United Kingdom": "English", "Australia": "English", "Canada": "English",
    "Spain": "English", "Mexico": "English", "Argentina": "English", "Colombia": "English",
    "France": "French", "Belgium": "French", "Senegal": "French",
    "Germany": "German", "Austria": "German", "Switzerland": "German",
    "Brazil": "English", "Portugal": "English",
    "Italy": "English",
    "Netherlands": "English",
    "Russia": "English", "Ukraine": "English",
    "China": "English",
    "Japan": "English",
    "South Korea": "English",
    "Saudi Arabia": "English", "United Arab Emirates": "English", "Egypt": "English", "Qatar": "English",
    "Iran": "English",
    "Turkey": "English",
    "India": "English"
};

// --- BELT SYSTEM CONSTANTS ---

export const WT_BELTS: Belt[] = [
    { id: 'wt-1', name: 'White Belt', color1: '#FFFFFF' },
    { id: 'wt-2', name: 'White/Yellow Stripe', color1: '#FFFFFF', color2: '#FFD700' },
    { id: 'wt-3', name: 'Yellow Belt', color1: '#FFD700' },
    { id: 'wt-4', name: 'Yellow/Green Stripe', color1: '#FFD700', color2: '#008000' },
    { id: 'wt-5', name: 'Green Belt', color1: '#008000' },
    { id: 'wt-6', name: 'Green/Blue Stripe', color1: '#008000', color2: '#0000FF' },
    { id: 'wt-7', name: 'Blue Belt', color1: '#0000FF' },
    { id: 'wt-8', name: 'Blue/Red Stripe', color1: '#0000FF', color2: '#FF0000' },
    { id: 'wt-9', name: 'Red Belt', color1: '#FF0000' },
    { id: 'wt-10', name: 'Red/Black Stripe', color1: '#FF0000', color2: '#000000' },
    { id: 'wt-11', name: 'Black Belt', color1: '#000000' }
];

export const ITF_BELTS: Belt[] = [
    { id: 'itf-1', name: 'White', color1: '#FFFFFF' },
    { id: 'itf-2', name: 'Yellow', color1: '#FFD700' },
    { id: 'itf-3', name: 'Orange', color1: '#FFA500' },
    { id: 'itf-4', name: 'Green', color1: '#008000' },
    { id: 'itf-5', name: 'Blue', color1: '#0000FF' },
    { id: 'itf-6', name: 'Purple', color1: '#800080' },
    { id: 'itf-7', name: 'Brown', color1: '#A52A2A' },
    { id: 'itf-8', name: 'Red', color1: '#FF0000' },
    { id: 'itf-9', name: 'Black', color1: '#000000' }
];

export const KARATE_BELTS: Belt[] = [
    { id: 'k-1', name: 'White', color1: '#FFFFFF' },
    { id: 'k-2', name: 'Yellow', color1: '#FFD700' },
    { id: 'k-3', name: 'Orange', color1: '#FFA500' },
    { id: 'k-4', name: 'Green', color1: '#008000' },
    { id: 'k-5', name: 'Blue', color1: '#0000FF' },
    { id: 'k-6', name: 'Purple', color1: '#800080' },
    { id: 'k-7', name: 'Brown (3rd Kyu)', color1: '#A52A2A' },
    { id: 'k-8', name: 'Brown (2nd Kyu)', color1: '#A52A2A' },
    { id: 'k-9', name: 'Brown (1st Kyu)', color1: '#A52A2A' },
    { id: 'k-10', name: 'Black', color1: '#000000' }
];

export const BJJ_BELTS: Belt[] = [
    { id: 'bjj-1', name: 'White', color1: '#FFFFFF' },
    { id: 'bjj-2', name: 'Blue', color1: '#0000FF' },
    { id: 'bjj-3', name: 'Purple', color1: '#800080' },
    { id: 'bjj-4', name: 'Brown', color1: '#A52A2A' },
    { id: 'bjj-5', name: 'Black', color1: '#000000' },
    { id: 'bjj-6', name: 'Red', color1: '#FF0000' }
];

export const JUDO_BELTS: Belt[] = [
    { id: 'j-1', name: 'White', color1: '#FFFFFF' },
    { id: 'j-2', name: 'Yellow', color1: '#FFD700' },
    { id: 'j-3', name: 'Orange', color1: '#FFA500' },
    { id: 'j-4', name: 'Green', color1: '#008000' },
    { id: 'j-5', name: 'Blue', color1: '#0000FF' },
    { id: 'j-6', name: 'Brown', color1: '#A52A2A' },
    { id: 'j-7', name: 'Black', color1: '#000000' }
];

export const HAPKIDO_BELTS: Belt[] = [
    { id: 'hkd-1', name: 'White', color1: '#FFFFFF' },
    { id: 'hkd-2', name: 'Yellow', color1: '#FFD700' },
    { id: 'hkd-3', name: 'Orange', color1: '#FFA500' },
    { id: 'hkd-4', name: 'Green', color1: '#008000' },
    { id: 'hkd-5', name: 'Blue', color1: '#0000FF' },
    { id: 'hkd-6', name: 'Brown', color1: '#A52A2A' },
    { id: 'hkd-7', name: 'Red', color1: '#FF0000' },
    { id: 'hkd-8', name: 'Black', color1: '#000000' }
];

export const TANGSOODO_BELTS: Belt[] = [
    { id: 'tsd-1', name: 'White', color1: '#FFFFFF' },
    { id: 'tsd-2', name: 'Orange', color1: '#FFA500' },
    { id: 'tsd-3', name: 'Green', color1: '#008000' },
    { id: 'tsd-4', name: 'Green (2 Stripes)', color1: '#008000' },
    { id: 'tsd-5', name: 'Red', color1: '#FF0000' },
    { id: 'tsd-6', name: 'Red (1 Stripe)', color1: '#FF0000' },
    { id: 'tsd-7', name: 'Red (2 Stripes)', color1: '#FF0000' },
    { id: 'tsd-8', name: 'Midnight Blue', color1: '#191970' }
];

export const AIKIDO_BELTS: Belt[] = [
    { id: 'aik-1', name: 'White (6th Kyu)', color1: '#FFFFFF' },
    { id: 'aik-2', name: 'Yellow (5th Kyu)', color1: '#FFD700' },
    { id: 'aik-3', name: 'Orange (4th Kyu)', color1: '#FFA500' },
    { id: 'aik-4', name: 'Green (3rd Kyu)', color1: '#008000' },
    { id: 'aik-5', name: 'Blue (2nd Kyu)', color1: '#0000FF' },
    { id: 'aik-6', name: 'Brown (1st Kyu)', color1: '#A52A2A' },
    { id: 'aik-7', name: 'Black (Shodan)', color1: '#000000' }
];

export const KRAVMAGA_BELTS: Belt[] = [
    { id: 'km-1', name: 'White (Practitioner 1)', color1: '#FFFFFF' },
    { id: 'km-2', name: 'Yellow (Practitioner 2)', color1: '#FFD700' },
    { id: 'km-3', name: 'Orange (Practitioner 3)', color1: '#FFA500' },
    { id: 'km-4', name: 'Green (Graduate 1)', color1: '#008000' },
    { id: 'km-5', name: 'Blue (Graduate 2)', color1: '#0000FF' },
    { id: 'km-6', name: 'Brown (Graduate 3)', color1: '#A52A2A' },
    { id: 'km-7', name: 'Black (Expert)', color1: '#000000' }
];

export const KUNGFU_BELTS: Belt[] = [
    { id: 'kf-1', name: 'White Sash', color1: '#FFFFFF' },
    { id: 'kf-2', name: 'Yellow Sash', color1: '#FFD700' },
    { id: 'kf-3', name: 'Orange Sash', color1: '#FFA500' },
    { id: 'kf-4', name: 'Green Sash', color1: '#008000' },
    { id: 'kf-5', name: 'Blue Sash', color1: '#0000FF' },
    { id: 'kf-6', name: 'Purple Sash', color1: '#800080' },
    { id: 'kf-7', name: 'Brown Sash', color1: '#A52A2A' },
    { id: 'kf-8', name: 'Red Sash', color1: '#FF0000' },
    { id: 'kf-9', name: 'Black Sash', color1: '#000000' }
];
